// #pragma once
#ifndef _APP_VERSION_H_
#define _APP_VERSION_H_
// #include "zephyr/include/generated/autoconf.h"
#ifdef CONFIG_SHIELD_KEYCHRON_V1_ULTRA_ANSI
#define APP_VERSION_MAJOR   1
#define APP_VERSION_MINOR   0
#define APP_PATCHLEVEL      2
#elif CONFIG_SHIELD_KEYCHRON_V0_ULTRA_ANSI
#define APP_VERSION_MAJOR   1
#define APP_VERSION_MINOR   0
#define APP_PATCHLEVEL      2
#elif CONFIG_SHIELD_KEYCHRON_V1_ULTRA_ISO
#define APP_VERSION_MAJOR   1
#define APP_VERSION_MINOR   0
#define APP_PATCHLEVEL      0
#elif CONFIG_SHIELD_KEYCHRON_V1_ULTRA_JP
#define APP_VERSION_MAJOR   1
#define APP_VERSION_MINOR   0
#define APP_PATCHLEVEL      0
#elif CONFIG_SHIELD_KEYCHRON_V2_ULTRA_ANSI
#define APP_VERSION_MAJOR   1
#define APP_VERSION_MINOR   0
#define APP_PATCHLEVEL      0
#elif CONFIG_SHIELD_KEYCHRON_V3_ULTRA_ANSI
#define APP_VERSION_MAJOR   1
#define APP_VERSION_MINOR   0
#define APP_PATCHLEVEL      1
#elif CONFIG_SHIELD_KEYCHRON_V5_ULTRA_ANSI
#define APP_VERSION_MAJOR   1
#define APP_VERSION_MINOR   0
#define APP_PATCHLEVEL      1
#elif CONFIG_SHIELD_KEYCHRON_V6_ULTRA_ANSI
#define APP_VERSION_MAJOR   1
#define APP_VERSION_MINOR   0
#define APP_PATCHLEVEL      1
#elif CONFIG_SHIELD_KEYCHRON_V10_ULTRA_ANSI
#define APP_VERSION_MAJOR   1
#define APP_VERSION_MINOR   0
#define APP_PATCHLEVEL      1
#elif  CONFIG_SHIELD_KEYCHRON_RS45_ANSI
#define APP_VERSION_MAJOR   1
#define APP_VERSION_MINOR   0
#define APP_PATCHLEVEL      0
#elif  CONFIG_SHIELD_KEYCHRON_RS87_ANSI
#define APP_VERSION_MAJOR   1
#define APP_VERSION_MINOR   0
#define APP_PATCHLEVEL      5
#elif  CONFIG_SHIELD_KEYCHRON_RS87U_ANSI
#define APP_VERSION_MAJOR   1
#define APP_VERSION_MINOR   0
#define APP_PATCHLEVEL      0
#elif  CONFIG_SHIELD_KEYCHRON_QN104_ANSI
#define APP_VERSION_MAJOR   1
#define APP_VERSION_MINOR   0
#define APP_PATCHLEVEL      0
#elif CONFIG_SHIELD_KEYCHRON_Q1_ULTRA_ANSI
#define APP_VERSION_MAJOR   1
#define APP_VERSION_MINOR   0
#define APP_PATCHLEVEL      1
#elif CONFIG_SHIELD_KEYCHRON_Q3_ULTRA_ANSI
#define APP_VERSION_MAJOR   1
#define APP_VERSION_MINOR   0
#define APP_PATCHLEVEL      1
#elif CONFIG_SHIELD_KEYCHRON_Q6_ULTRA_ANSI
#define APP_VERSION_MAJOR   1
#define APP_VERSION_MINOR   0
#define APP_PATCHLEVEL      2
#else
#define APP_VERSION_MAJOR   1
#define APP_VERSION_MINOR   0
#define APP_PATCHLEVEL      0
#endif 

#define APP1_(a,b,c) #a"."#b"."#c
#define APP2_(a,b,c) APP1_(a,b,c)
#define APP_VERSION_STRING APP2_(APP_VERSION_MAJOR,APP_VERSION_MINOR,APP_PATCHLEVEL)

#endif /* _APP_VERSION_H_ */
