#ifndef __MY_DFU_PRIVATE_H__
#define __MY_DFU_PRIVATE_H__

#include "app_version.h"

#define DUAL_IMAGE_HDR 0
#define SC_FILE_FORMAT_KFW 1
#ifdef CONFIG_SHIELD_KEYCHRON_V1_ULTRA_ANSI
#define MY_FWU_STRING_NAME "KCZKV18K"
#elif CONFIG_SHIELD_KEYCHRON_V0_ULTRA_ANSI
#define MY_FWU_STRING_NAME "KCZKV08K"
#elif CONFIG_SHIELD_KEYCHRON_V1_ULTRA_ISO
#define MY_FWU_STRING_NAME "KCZKV18I"
#elif CONFIG_SHIELD_KEYCHRON_V1_ULTRA_JP
#define MY_FWU_STRING_NAME "KCZKV18J"
#elif CONFIG_SHIELD_KEYCHRON_V2_ULTRA_ANSI
#define MY_FWU_STRING_NAME "KCZKV28K"
#elif CONFIG_SHIELD_KEYCHRON_V3_ULTRA_ANSI
#define MY_FWU_STRING_NAME "KCZKV38K"
#elif CONFIG_SHIELD_KEYCHRON_V5_ULTRA_ANSI
#define MY_FWU_STRING_NAME "KCZKV58K"
#elif CONFIG_SHIELD_KEYCHRON_V6_ULTRA_ANSI
#define MY_FWU_STRING_NAME "KCZKV68K"
#elif CONFIG_SHIELD_KEYCHRON_V10_ULTRA_ANSI
#define MY_FWU_STRING_NAME "KCZKVA8K"
#elif CONFIG_SHIELD_KEYCHRON_RS45_ANSI
#define MY_FWU_STRING_NAME "KCQLRS45"
#elif CONFIG_SHIELD_KEYCHRON_RS87_ANSI
#if CONFIG_SHIELD_KEYCHRON_RS87U_ANSI
#define MY_FWU_STRING_NAME "KCQL87UL"
#else
#define MY_FWU_STRING_NAME "KCQLRS87"
#endif
#elif CONFIG_SHIELD_KEYCHRON_QN104_ANSI
#define MY_FWU_STRING_NAME "KCQN1048"
#elif CONFIG_SHIELD_KEYCHRON_Q1_ULTRA_ANSI
#define MY_FWU_STRING_NAME "KCZKQ18K"
#elif CONFIG_SHIELD_KEYCHRON_Q3_ULTRA_ANSI
#define MY_FWU_STRING_NAME "KCZKQ38K"
#elif CONFIG_SHIELD_KEYCHRON_Q6_ULTRA_ANSI
#define MY_FWU_STRING_NAME "KCZKQ68K"
#elif CONFIG_SHIELD_KEYCHRON_K3SE2_ANSI
#define MY_FWU_STRING_NAME "KCZK3SE2"
#elif CONFIG_SHIELD_KEYCHRON_K5SE2_ANSI
#define MY_FWU_STRING_NAME "KCZK5SE2"
#elif CONFIG_SHIELD_KEYCHRON_Z270_ANSI
#define MY_FWU_STRING_NAME "KCZ270U"
#else
#define MY_FWU_STRING_NAME "KCZKK10M"
#endif
#if CONFIG_LOG
#define MY_FW_VERSION APP_VERSION_STRING "-d"
#else
#define MY_FW_VERSION APP_VERSION_STRING "-r"
#endif
#define MY_HW_VERSION "v1.0.0"
unsigned char *my_dfu_get_prv_data(void);
unsigned char my_dfu_get_prv_len(void);

#if (DUAL_IMAGE_HDR)
unsigned char *my_dfu_get_prv_data_fixes(void);
unsigned char my_dfu_get_prv_len_fixes(void);
#endif

#endif
