#ifndef __RGB_MATRIX_CONF_H__
#define __RGB_MATRIX_CONF_H__
#include <stdint.h>
#include <zmk/matrix.h>




#define ENABLE_RGB_EFFECT_SOLID_COLOR           //1
#define ENABLE_RGB_EFFECT_BREATHING             //2
#define ENABLE_RGB_EFFECT_SPIRAL_BRIGHTNESS     //3
#define ENABLE_RGB_EFFECT_CYCLE_ALL             //4
#define ENABLE_RGB_EFFECT_CYCLE_LEFT_RIGHT      //5
#define ENABLE_RGB_EFFECT_CYCLE_UP_DOWN         //6
#define ENABLE_RGB_EFFECT_RAINBOW_MOVING        //7
#define ENABLE_RGB_EFFECT_CYCLE_OUT_IN          //8
#define ENABLE_RGB_EFFECT_CYCLE_OUT_IN_DUAL     //9
#define ENABLE_RGB_EFFECT_CYCLE_PINWHEEL        //10
#define ENABLE_RGB_EFFECT_CYCLE_SPIRAL          //11
#define ENABLE_RGB_EFFECT_SPIN_AROUND_CENTER    //12
#define ENABLE_RGB_EFFECT_RAINBOW_SPIN          //13
#define ENABLE_RGB_EFFECT_RANDOM_RAINDROPS      //14
#define ENABLE_RGB_EFFECT_RANDOM_LIGHT_KEY      //15
#define ENABLE_RGB_EFFECT_TYPING_HEATMAP        //16
#define ENABLE_RGB_EFFECT_DIGITAL_RAIN          //17
#define ENABLE_RGB_EFFECT_SOLID_REACTIVE_SIMPLE //18
#define ENABLE_RGB_EFFECT_SOLID_REACTIVE_MULTIWIDE  //19    
#define ENABLE_RGB_EFFECT_SOLID_REACTIVE_MULTINEXUS //20
#define ENABLE_RGB_EFFECT_SPLASH                    //21
#define ENABLE_RGB_EFFECT_SOLID_SPLASH              //22
#ifdef CONFIG_KEYCHRON_RGB_ENABLE
#define ENABLE_RGB_EFFECT_MIXED_RGB                 //23
#define ENABLE_RGB_EFFECT_PER_KEY_RGB               //24
#endif 
// #define ENABLE_RGB_EFFECT_RUN                       //23


enum rgb_effects {
    RGB_EFFECT_NONE = 0,
#ifdef ENABLE_RGB_EFFECT_SOLID_COLOR
    RGB_EFFECT_SOLID_COLOR,
#endif 
#ifdef ENABLE_RGB_EFFECT_BREATHING
    RGB_EFFECT_BREATHING,
#endif 
#ifdef ENABLE_RGB_EFFECT_SPIRAL_BRIGHTNESS
    RGB_EFFECT_SPIRAL_BRIGHTNESS,
#endif     
#ifdef ENABLE_RGB_EFFECT_CYCLE_ALL
    RGB_EFFECT_CYCLE_ALL,
#endif    
#ifdef ENABLE_RGB_EFFECT_CYCLE_LEFT_RIGHT
    RGB_EFFECT_CYCLE_LEFT_RIGHT,
#endif 
#ifdef ENABLE_RGB_EFFECT_CYCLE_UP_DOWN
    RGB_EFFECT_CYCLE_UP_DOWN,
#endif   
#ifdef ENABLE_RGB_EFFECT_RAINBOW_MOVING
    RGB_EFFECT_RAINBOW_MOVING,
#endif   
#ifdef ENABLE_RGB_EFFECT_CYCLE_OUT_IN
    RGB_EFFECT_CYCLE_OUT_IN,
#endif   
#ifdef ENABLE_RGB_EFFECT_CYCLE_OUT_IN_DUAL
    cycle_out_in_dual,
#endif   
#ifdef ENABLE_RGB_EFFECT_CYCLE_PINWHEEL
    RGB_EFFECT_CYCLE_OUT_IN_DUAL,
#endif  
#ifdef ENABLE_RGB_EFFECT_CYCLE_SPIRAL
    RGB_EFFECT_CYCLE_SPIRAL,
#endif    
#ifdef ENABLE_RGB_EFFECT_SPIN_AROUND_CENTER
    RGB_EFFECT_SPIN_AROUND_CENTER,
#endif 
#ifdef ENABLE_RGB_EFFECT_RAINBOW_SPIN
    RGB_EFFECT_RAINBOW_SPIN,
#endif 
#ifdef ENABLE_RGB_EFFECT_RANDOM_RAINDROPS
    random_raindrops,
#endif  
#ifdef ENABLE_RGB_EFFECT_RANDOM_LIGHT_KEY
    RGB_EFFECT_RANDOM_RAINDROPS,
#endif    
#ifdef ENABLE_RGB_EFFECT_TYPING_HEATMAP
    RGB_EFFECT_TYPING_HEATMAP,
#endif 
#ifdef ENABLE_RGB_EFFECT_DIGITAL_RAIN
    RGB_EFFECT_DIGITAL_RAIN,
#endif  
#ifdef ENABLE_RGB_EFFECT_SOLID_REACTIVE_SIMPLE
    RGB_EFFECT_SOLID_REACTIVE_SIMPLE,
#endif
#ifdef ENABLE_RGB_EFFECT_SOLID_REACTIVE_MULTIWIDE
    RGB_EFFECT_SOLID_REACTIVE_MULTIWIDE,
#endif   
#ifdef ENABLE_RGB_EFFECT_SOLID_REACTIVE_MULTINEXUS
    RGB_EFFECT_SOLID_REACTIVE_MULTINEXUS,
#endif
#ifdef ENABLE_RGB_EFFECT_SPLASH
    RGB_EFFECT_SPLASH,
#endif 
#ifdef ENABLE_RGB_EFFECT_SOLID_SPLASH
    RGB_EFFECT_SOLID_SPLASH,
#endif  
#ifdef ENABLE_RGB_EFFECT_PER_KEY_RGB
    RGB_EFFECT_PER_KEY_RGB,
#endif 
#ifdef ENABLE_RGB_EFFECT_MIXED_RGB
    RGB_EFFECT_MIXED_RGB,
#endif 

#ifdef ENABLE_RGB_EFFECT_RUN
    RGB_EFFECT_RUN,
#endif         

    RGB_EFFECT_MAX
};

#define RGB_MATRIX_HUE_STEP 8
#define RGB_MATRIX_SAT_STEP 16
#define RGB_MATRIX_VAL_STEP 20
#define RGB_MATRIX_SPD_STEP 16
#define RGB_MATRIX_DEFAULT_ON true
#define RGB_MATRIX_DEFAULT_MODE RGB_EFFECT_CYCLE_LEFT_RIGHT
#define RGB_MATRIX_DEFAULT_HUE 0
#define RGB_MATRIX_DEFAULT_SAT UINT8_MAX
#define RGB_MATRIX_DEFAULT_VAL RGB_MATRIX_MAXIMUM_BRIGHTNESS
#define RGB_MATRIX_DEFAULT_SPD (UINT8_MAX / 2)
#define RGB_MATRIX_LED_FLUSH_LIMIT 18//16
#define RGB_MATRIX_LED_PROCESS_LIMIT ((RGB_MATRIX_LED_COUNT + 1) / 2)//((RGB_MATRIX_LED_COUNT + 4) / 5)
#define LED_HITS_TO_REMEMBER 8
#define RGB_MATRIX_MAXIMUM_BRIGHTNESS UINT8_MAX

#define MATRIX_ROWS  (ZMK_MATRIX_ROWS-1)
#define MATRIX_COLS  ZMK_MATRIX_COLS

#if CONFIG_SHIELD_KEYCHRON_V1_ULTRA_ANSI
#include "v1_ultra_rgb_index.h"
#elif CONFIG_SHIELD_KEYCHRON_V1_ULTRA_ISO
#include "v1_ultra_iso_rgb_index.h"
#elif CONFIG_SHIELD_KEYCHRON_V1_ULTRA_JP
#include "v1_ultra_jp_rgb_index.h"
#elif CONFIG_SHIELD_KEYCHRON_V2_ULTRA_ANSI
#include "v2_ultra_rgb_index.h"
#elif CONFIG_SHIELD_KEYCHRON_V3_ULTRA_ANSI
#include "v3_ultra_rgb_index.h"
#elif CONFIG_SHIELD_KEYCHRON_V5_ULTRA_ANSI
#include "v5_ultra_rgb_index.h"
#elif CONFIG_SHIELD_KEYCHRON_V6_ULTRA_ANSI
#include "v6_ultra_rgb_index.h"
#elif CONFIG_SHIELD_KEYCHRON_V10_ULTRA_ANSI
#include "v10_ultra_rgb_index.h"
#elif CONFIG_SHIELD_KEYCHRON_Q1_ULTRA_ANSI
#include "q1ultra_rgb_index.h"
#elif CONFIG_SHIELD_KEYCHRON_Q3_ULTRA_ANSI
#include "q3ultra_rgb_index.h"
#elif CONFIG_SHIELD_KEYCHRON_Q6_ULTRA_ANSI
#include "q6_ultra_rgb_index.h"
#elif CONFIG_SHIELD_KEYCHRON_V0_ULTRA_ANSI
#include "v0_ultra_rgb_index.h"
#elif CONFIG_SHIELD_KEYCHRON_Z270_ANSI
#include "z270_ultra_rgb_index.h"
#else
#error "none"
#endif 

#endif 