#original
#CONFIG_USB_DEVICE_PRODUCT="Keychron B1 Pro"
#CONFIG_BT_DIS_MODEL="Keychron B1 pro"
#CONFIG_ZMK_KEYBOARD_NAME="Keychron B1 Pro"
#
#CONFIG_USB_DEVICE_VID=0x3434
#CONFIG_USB_DEVICE_PID=0x0711
#CONFIG_BT_DIS_PNP_VID=0x3434
#CONFIG_BT_DIS_PNP_PID=0x0711
#CONFIG_BT_DIS_FW_REV_STR="v1.0.4"
#CONFIG_BT_DIS_HW_REV_STR="v1.0.0"
#CONFIG_BT_DIS_SERIAL_NUMBER_STR="SN2024040814230078"

#New

# 1. Disable Wireless to reclaim ~30% of Total Flash
CONFIG_ZMK_BLE=n
CONFIG_BT=n

# 2. Increase Macro Capacity (Default is 64)
# Allows a single macro to type ~256 characters
CONFIG_ZMK_BEHAVIORS_QUEUE_SIZE=512

# 3. Maintain HP Identity
CONFIG_USB_DEVICE_VID=0x03F0
CONFIG_USB_DEVICE_PID=0x564A
CONFIG_USB_DEVICE_MANUFACTURER="HP"
CONFIG_USB_DEVICE_PRODUCT="HP Keyboard"
CONFIG_ZMK_KEYBOARD_NAME="HP Keyboard"

# 4. Wired Performance Optimization
CONFIG_USB_HID_POLL_INTERVAL_MS=1
